### ISSUE TITLE
Asking about how to run the eval script for AE

### ISSUE THREAD

**Issue by fajarmuslim** [howardhsu/BERT-for-RRC-ABSA#24]
![AE](https://user-images.githubusercontent.com/42022311/132243629-0b2b9b0d-f48e-41ce-b609-73ff4579dcf2.png)

what is the right terminal command? I have try to use `python evaluate_ae.py --pred_json rest` but found an error like bellow

`Traceback (most recent call last):
  File "evaluate_ae.py", line 174, in <module>
    print(evaluate(args.pred_json, command, template) )
  File "evaluate_ae.py", line 136, in evaluate
    with open(pred_fn) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'rest'
`
what can I do? to solve this problem?

**Comment by fajarmuslim** [comment]
I can figure out it now, thank you....
